### PR TITLE
Fix bitmap base conversion

### PR DESCRIPTION
**Pull request by kaperys**

### CODE REVIEW

**Comment by m1ome** [comment]
@kaperys can you provide some additional test over this issue. I mean it would be awesome if it will be covered in test suite. Thank you!

**Comment by kaperys** [comment]
@m1ome I've removed the bitmap length check that that was causing the coverage to drop (it never got hit because the padding happens when the base is converted from 16 to 2)

**Comment by m1ome** [comment]
@kaperys I mean not improve code coverage, but to provide case in test suite that covers your issue.

**Comment by kaperys** [comment]
@m1ome sorry, covered! I've also added a couple of example files which I've been using whilst playing around

**Comment by m1ome** [comment]
@kaperys Awesome thank you for a job!

**Pull request merged**
